### ISSUE TITLE
Optional arguments

### ISSUE THREAD

**Issue by dclew** [wvandeun/nornir_netbox#19]
Is there a way to pass optional arguments to the inventory? Maybe I'm missing something. When I use SimpleInventory in Nornir, I'm able to pass optional arguments for each host in the host file such:

```
HOSTNAME:
  hostname: 1.1.1.1
  platform: 'ios'
  username: -
  password: -
  connection_options:
    netmiko:
      extras:
        device_type: 'cisco_ios'
        global_delay_factor: 2
    napalm:
      extras:
        optional_args:
          global_delay_factor: 2
```

How do you pass global_delay_factor and other optional arguments into Nornir using this inventory plugin?
