### ISSUE TITLE
Problem with connection options 

### ISSUE THREAD

**Issue by Sivolen** [wvandeun/nornir_netbox#37]
Hi!
I made a config and added timeout parameters there, but nornir does not perceive them, can you tell me why? 
```
inventory:
  plugin: NetBoxInventory2
  options:
#    nb_url: 'http://127.0.0.1'
    nb_token: ' '
    ssl_verify: False
    use_slugs: True
    flatten_custom_fields: True
    use_platform_napalm_driver: True
    filter_parameters:
        role: ["cs"]
    connection_options:
      netmiko:
        extras:
          conn_timeout: 20
      paramiko:
         extras:
          conn_timeout: 20
```
