### ISSUE TITLE
Connection aborted

### ISSUE THREAD

**Issue by gbs098** [wvandeun/nornir_netbox#49]
Hello, how can ignore proxy?
Have tried like what but dosen't work
```
inventory:
  plugin: NetBoxInventory2
  options:
    nb_url: "https://nb_test/"
    nb_token: "*****"
    ssl_verify: False
    proxies:
      http: ""
      https: ""
```
